### ISSUE TITLE
Как запустить?

### ISSUE THREAD

**Issue by Kew1e** [iwdok/1xBetBot#1]
Привет, мне очень понравился твой бот, но по коду я не очень понял как он ставит, и как запустить его? Именно через консольные на Линуксе, какие команды нужны

**Comment by iwdok** [comment]
Привет, извиняюсь что только сейчас отвечаю, этот проект был коммерческим, но все оборвалось и я им не занимался, случайно заметил, npm start запускает бот

**Comment by Kew1e** [comment]
спс)
